# @name test
GET http://localhost:3000/test 

###

# @name criar_habito
POST http://localhost:3000/habits
content-type: application/json

{
    "title": "Estudar",
    "weekDays": [2, 3, 4]
}

###

# @name get_day
GET http://localhost:3000/day?date=2023-01-02T03%3A00%3A00.000z

